# @package _global_
device: "cuda"
limit: null

defaults:
  - /dataset: grandtour_raw
  - /model: pivot
  - _self_

dataset:
  name: grandtour_raw
  split: full
  do_augmentation: false

model:
  name: pivot

loader:
  batch_size: 1
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false

eval:
  logging:
    out_dir: "outputs/eval/${now:%Y%m%d}-${now:%H%M%S}"

  metrics:
    - name: compute_accuracy
      kwargs:
        arcs: "outputs/motion_arcs"
        pred: "outputs/action_preds"
        odom: "inputs/action_label"

    - name: compute_hausdorff_distance
      kwargs:
        arcs: "outputs/motion_arcs"
        pred: "outputs/action_preds"
        odom: "inputs/action_label"

    - name: compute_relative_hausdorff_distance
      kwargs:
        arcs: "outputs/motion_arcs"
        pred: "outputs/action_preds"
        odom: "inputs/action_label"
